#!/bin/sh
# detritusd -- runit run script
#
# The binary is foreground: it blocks in epoll_wait and does not
# daemonize. runsv is the supervisor. Do not background here.
exec 2>&1
[ -r /etc/conf.d/detritus ] && . /etc/conf.d/detritus
export DETRITUS_NOTIFY_USER
exec /usr/local/sbin/detritusd
